# Generated by Django 3.1.2 on 2020-10-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_act",
                    models.CharField(max_length=15, verbose_name="demanda"),
                ),
                (
                    "system_name",
                    models.CharField(max_length=10, verbose_name="sistema"),
                ),
                (
                    "description",
                    models.TextField(max_length=100, verbose_name="descrição"),
                ),
                (
                    "date_act",
                    models.DateTimeField(
                        help_text="A data em que a atividade foi realizada.",
                        verbose_name="data",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("C", "Concluída"),
                            ("E", "Em Execução"),
                            ("R", "Rejeitada"),
                        ],
                        max_length=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Comentários sobre o que foi feito na atividade.",
                        max_length=4000,
                        verbose_name="comentário",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="criado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Atividade",
                "verbose_name_plural": "Atividades",
            },
        )
    ]
