# Generated by Django 3.1.2 on 2020-10-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ("-date_act",),
                "verbose_name": "Atividade",
                "verbose_name_plural": "Atividades",
            },
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(
                help_text="Descrição sobre o que deve ser feito na atividade.",
                max_length=100,
                verbose_name="descrição",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="num_act",
            field=models.CharField(
                blank=True,
                help_text="Identificação da atividade.",
                max_length=30,
                verbose_name="demanda",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Concluída"),
                    ("E", "Em Execução"),
                    ("R", "Rejeitada"),
                ],
                help_text="Flag para indicar qual a situação da atividade.",
                max_length=1,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="system_name",
            field=models.CharField(
                blank=True,
                help_text="Sigla do sistema.",
                max_length=10,
                verbose_name="sistema",
            ),
        ),
    ]
