# Generated by Django 3.1.2 on 2020-10-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0002_auto_20201012_1804")]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(
                help_text="Descrição sobre o que deve ser feito na atividade.",
                max_length=4000,
                verbose_name="descrição",
            ),
        )
    ]
